# Generated by Django 2.1.1 on 2018-10-18 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demograph', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maptype',
            name='choice_text',
        ),
        migrations.RemoveField(
            model_name='maptype',
            name='question',
        ),
        migrations.RemoveField(
            model_name='maptype',
            name='votes',
        ),
        migrations.AddField(
            model_name='maptype',
            name='map_type',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Title',
        ),
    ]
